### ISSUE TITLE
RangeError: Mark decorations may not be empty

### ISSUE THREAD

**Issue by tadashi-aikawa** [kometenstaub/obsidian-vim-yank-highlight#2]
Hi, @kometenstaub. I found the bug that only occurs in new windows.

**Reproduction procedure**

1. Open sandbox vault
2. Enable `Vim key bindings`
3. Install and enable `BRAT`
4. Install `obsidian-vim-yank-highlight` via BRAT and enable it
5. Exec `Open in new window` in `Start Here.md`
6. Yank first line by `yy`
7. Paste it to the next line **by paste command of system clipboard (ex: Ctrl+v in Windows) NOT PUT COMMAND OF VIM**
8. Yank this line by `ESCyy`

![image](https://user-images.githubusercontent.com/9500018/177043859-d2bc16af-ae05-4596-9cd3-80db8f18c662.png)

- Obsidian version: v0.15.3
- Vim Yank Highlighter: v1.1.3
- OS: Windows10

Best regards.

**Comment by kometenstaub** [comment]
![screenshot](https://user-images.githubusercontent.com/83140328/177053332-5763ba11-e5a5-45a6-a596-ca452e8b0a66.png)

The repro is hitting escape in vim. Go to insert mode, hit Esc. (Doesn't matter whether it is `i` or `A` and then `Esc` for example.)

In that case with `yy` you get the same error from, because it gets the same result for the beginning and end of the line (sometimes it takes the end, a bit rarer the beginning).

`yy` proceeds to doing the browser highlight.

Switching out of the window and back restores it. This must be an issue with how `Esc` is handled in pop-out windows.

**Comment by kometenstaub** [comment]
Hm, I cannot repro the vim error without this plugin.

**Comment by kometenstaub** [comment]
I think I know the issue. When hitting Escape, the active view switches back to the last active editor in the main window, which it shouldn't.

So it chooses the wrong editor for getting the highlight position.

**Comment by kometenstaub** [comment]
Should get fixed in the next insider build.

**Comment by tadashi-aikawa** [comment]
Thank you for your reply :)

> I think I know the issue. When hitting Escape, the active view switches back to the last active editor in the main window, which it shouldn't.

Ah.. I know the problem and have been annoying. I am looking forward to fix it 😄

**Comment by kometenstaub** [comment]
It's fixed in Obsidian 0.15.4.
